services:
  db-prod:
    image: postgres:15
    environment:
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
      POSTGRES_DB: hackhub_db
    ports:
      - "5432:5432"

  backend:
    build: ./hackhub_backend # Sostituisci col path corretto
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:postgresql://db-prod:5432/hackhub_db
      - DB_USERNAME=dev_user
      - DB_PASSWORD=dev_password
      - APP_PEPPER=SegretoTest123!
      - JWT_SECRET=SecretTest9f8a2c7e1b4d6f0a5e3c9d7b2a1f8e4c
    depends_on:
      - db-prod

  frontend:
    build: ./hackhub_frontend # Sostituisci col path corretto
    ports:
      - "4200:80" # Mappiamo la porta 80 di Nginx sulla 4200 del tuo PC
    depends_on:
      - backend