app.cors.allowed-origins=${CORS_URL}
app.security.password-pepper=${PASSWORD_PEPPER}

# Database di Produzione (es. PostgreSQL)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

#JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
